[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mcpepe_presale = "4ZD9bhpiwwaL1hxutSmW2hcHaAVzru28niPXhqXrEjLP"

[programs.localnet]
mcpepe_presale = "4ZD9bhpiwwaL1hxutSmW2hcHaAVzru28niPXhqXrEjLP"

[programs.mainnet]
mcpepe_presale = "4ZD9bhpiwwaL1hxutSmW2hcHaAVzru28niPXhqXrEjLP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false
